name: "build and push"
on:
  push:
    branches:
      - go

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    container: docker:latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: go
      - name: build
        run: apk add libc6-compat --no-cache && ./build-go.sh
      - name: docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: echo ${DOCKER_ACCESS_TOKEN} | docker login --username ${DOCKER_USERNAME} --password-stdin
